### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by IP-CAM** [IP-CAM/OC1.5.6.5-LIGHT#1]
IMPORTANT: In the VQMOD Directory, a **vqcache**  and a **logs** subdirectory needs to be added, to make install work. Also, a system/**cache**/ and image/**cache**/ directory need to be created manually, respectively, need to be added into the Upload.

Also all the -go to Top- files have been removed now, since another easier routine has been implemented. For some reason, the still existed, and it added a funny **toTop** Word in the Footer at the end of the page displayed ...

**Comment by condor2** [comment]
Added
